#+TITLE: Homepage of Simin Yang
#+AUTHOR: Simin Yang
#+EMAIL: smyang.ustc@gmail.com
#+OPTIONS: toc:nil
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:showall tdepth:nil ltoc:nil

* 工作经历
上海淘米网络科技有限公司，中国最为领先的儿童娱乐媒体公司，NYSE上市企业。2010年07月至今
 + 运维系统，C/C++后台开发工程师，2012年07月至今
该系统综合了Ganglia的实时状态图、Nagios的异常告警，整合了资产管理和数据库管理等功能，以方便运维人员对线上500余台服务器和交换机进行管理。本人全面负责运维系统的后台研发工作，带领三个人的小团队，使用统一的异步服务器框架，快速构建具有集中分发、透明代理等模块的多层次网络架构。期间还辅导一名应届生顺利转正。

 + 数据分析中心，Linux后台开发工程师，2012年12月至今
使用Hadoop对线上玩家的登录、充值、消费等数据进行分析。对每个游戏产品，给出PV/UV、新增/活跃/留存/回流、付费ARPU/渗透率等关键数据，为线上游戏的科学决策和品质运营提供服务。负责编写数据分析用的部分Mapper/Reducer代码，及时比照检查结果数据的准确性。

 + 射击类竞技页游《凯特战争》，C/C++后台开发工程师，2011年11月 - 2012年06月
《凯特战争》是淘米首款采用与《魔兽世界》类似的大区小服结构的页游。期间，接触到多层次的网络后台系统架构，学习了健壮性可扩展性系统设计。特别是使用epoll模型的异步服务器框架后，数据存取、业务处理和数据转发的分层次设计。通过降低模块之间的耦合性，提升灵活度，来适应运营中大区小服开荒、合并的需求。

 + 社区游戏《摩尔斗斗》，C/C++后台开发工程师，2010年12月 - 2011年11月
《摩尔斗斗》是国内首款儿童社区游戏，在人人网、新浪微游戏、开心网和淘米校巴等平台运营。其中，在人人网一度达到2.5万日活跃用户，位居最活跃排行榜第一，销售排行榜前三，被推荐为热门游戏。从游戏立项到研发上线，再到后期运营拓展，经历了完整的游戏生命过程，从对游戏后台零概念开始，逐步学习成长为后台负责人。

 + 流量统计系统，C/C++软件开发工程师，2010年07月 - 2010年12月
实现与Google Analytics类似的PV/UV/IP分类统计功能。对公司的所有对外web页面，提供精确到分、延迟不超过5分钟的实时数据，以及15分钟、1小时、1天等精度的汇总数据。使用分布式文件系统MooseFS解决了大量数据的分布式存取、处理的问题。应用mmap和红黑树算法，提升了大量Key-Value数据的实时统计效率。该项目获得领导的一致好评。

* 教育背景
中国科学技术大学
 + 硕士，计算机软件与理论，计算机科学与技术学院，2007年09月-2010年06月
 + 本科，信息与计算数学，数学系，2003年09月-2007年06月
 + 双学位，金融学，统计与金融系，2005年01月-2007年06月

* 专业技术
 + CET-6，较好的英文读写能力
 + 掌握C/C++，十万行以上代码经验，熟悉Shell编程，了解Python、PHP和Java编程
 + 掌握MySQL编程，了解Memcache、Berkeley DB和Hadoop的基本用法
 + 两年以上Linux环境开发经验，能熟练使用vim/make/gdb/valgrind等开发、调试、测试工具
 + 熟悉Linux下网络编程，了解编译器技术，特别是后端的代码生成和优化
 + 掌握Linux系统常用应用服务配置、维护，知晓常用的性能调优方法

* 自我评价
 + 工作认真，注重细节，信守承诺，勇于开拓创新
 + 兴趣广泛，好奇心强，喜欢钻研新技术，学习能力突出，接受新鲜事物较快
 + 团队意识良好，主动承担相关责任，并积极配合他人按时按质完成工作，保证团队进度

* 荣誉奖励
 + 上海淘米网络科技有限公司。2010年最佳新人奖
 + 中国科学技术大学。2005年优秀学生奖学金；2004年三浦奖学金；2003年优秀新生奖学金

* 个人信息
男，1985年10月生，目前居住在上海
