#! /usr/bin/env python
def main(argv):
        if len(argv)!=2:
                print 'Please use 1 option'
                return 0
        else:
                content=argv[1]
                content=re.sub(r'\n$','',content)
                gbkURL=urllib.quote(content)
                gbkURL=re.sub(r'^rtsp%3A','rtsp:',gbkURL)
                print gbkURL

if __name__=="__main__":
        try: import urllib,re,sys
        except ImportError:
                print 'Please Check that you have sys,os,re,urllib modules'
        main(sys.argv) 
