#+TITLE:     Joint Training Plan
#+AUTHOR:    Zhong Zhuang
#+EMAIL:     dyzz@mail.ustc.edu.cn
#+DATE:      2009-12-15 
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   toc:nil
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc


* Research Topic and Background
  + *Topic:* /Automated Theorem Prover and Implementation/
  + *Background:* Certifying compiler is a way to build high-confidence software. Most of them follow the Hoare-style logic, 
    and verfify programs by proving assertions generated by the compiler. These proof can be given by hand or by 
    automated theorem prover(ATP). The difficulties are if we need to verify complicated 
    properties of programs, ATPs nowadays are not capable to deal with and if we need to 
    verify large scale programs, these assertions can be exausting for human. This research 
    came from the operation system kernel verification of previous work in our lab and aims at
    automated theorem prover development and programming language support. 

* Collarborative Tutors
  Prof. Yiyun Chen  Department of Computer Science and Technology, USTC
  Prof. Zhong Shao  Department of Computer Science and Technology, Yale

  This student has been in the Research Center for High Confidence Software of
  USTC--Yale. The center is a platform for tutors and graduate students of two
  schools in related fields to carry out collaborative research and strengthen
  academic exchanges, it also enhance the research level for teachers and students
  ofUSTC.

* Domestic Research Preparation
  In the past two years I have taken charge of a certifying compiler project and developed 
  automated theorem prover for separation logic both in SML/NJ and Coq Proof Assistant. 
  I have accumulated a lot of theoretical and technical foundation from this project.

  *Theoretical Foundation:* In the period I have a profound understanding of PCC
  Framework, Programming Theory, Hoare Logic, Separation Logic and Decision Procedures. 
    
  *Technical Foundation:* During the work of program verification I benefited with
  a lot of experience and technical foundation, such as Separation Logic, Invariance Proof 
  and the use of Coq Proof Assistant.

* Training Program During PhD
  1) *The first year:* take charge of the certifying compiler project

  2) *The second year:* research topic about more practical ATP for separation logic 

  3) *The third year:* study and research in Yale
     
  4) *After back:* finish the PhD. thesis and thesis defense.

* Objective of Studying Abroad
  I will continue with the research of ATP, and improve current proof automation mechnisms in Coq and 
  programming language support for ATP. During the period that abroad one or two papers about the research results will be
  published on the international conferences or journals.
