#+TITLE:     客户端与服务器通讯协议
#+AUTHOR:    smyang
#+EMAIL:     smyang@taomee.com
#+DATE:      2010-12-22
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   toc:nil
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:showall



* Research Topic and Background
  + *Topic:* /Automated Theorem Prover and Implementation/
  + *Background:* Certifying compiler is a way to build high-confidence software. Most of them follow the Hoare-style logic, 
    and verify programs by proving assertions generated by the compiler. These proof can be given by hand or by 
    automated theorem prover(ATP). The difficulties are if we need to verify complicated 
    properties of programs, ATPs nowadays are not capable to deal with and if we need to 
    verify large scale programs, these assertions can be exhausting for human. This research 
    came from the certifying compiler project and operation system kernel verification in our lab and aims at
    automated theorem prover development and programming language support. 

* Collaborative Tutors
  Prof. Yiyun Chen  Department of Computer Science and Technology, USTC
  Prof. Zhong Shao  Department of Computer Science and Technology, Yale

  This student has been in the Research Center for High Confidence Software of
  USTC--Yale. The center is a platform for tutors and graduate students of two
  schools in related fields to carry out collaborative research and strengthen
  academic exchanges, it also enhances the research level for teachers and students
  of USTC.

* Domestic Research Preparation
  In the past two years I have taken charge of a certifying compiler project and developed 
  automated theorem prover for separation logic both in SML/NJ and Coq Proof Assistant. 
  I have accumulated a lot of theoretical and technical foundation from this project.

  *Theoretical Foundation:* In the period I have a profound understanding of PCC
  Framework, Certifying Compiler, Certified Compiler, Programming Theory, Hoare Logic, Separation Logic, Decision Procedures and
  Proof Automation. 
    
  *Technical Foundation:* During the work of program verification I benefited with
  a lot of experience and technical foundation, such as decision procedure for separation logic, 
  proof objects generation and proof automation in Coq proof assistant.

* Training Program During PhD
  1) *The first year:* take charge of the certifying compiler project

  2) *The second year:* research topic about more practical ATP for separation logic 

  3) *The third year:* study and research in Yale
     
  4) *After back:* finish the PhD. thesis and thesis defense.

* Objective of Studying Abroad
  I will continue with the research of ATP, and improve current proof automation mechanisms in Coq and 
  programming language support for ATP. During the period that abroad one or two papers about the research results will be
  published on the international conferences or journals.
