实验室网站改进计划

* Publication
目前存在的问题是各个小组的Publication都集中在一个页面,且没有分类和排序,检索困难.

** 解决方法
考虑到工作量不大, 这部分计划重新进行内容添加. 目前在系统中新增了"Paper"类型的内容供创建, 在"Create Content"下选择"Paper"进行内容添加, 提供的字段包括:

| 字段     | 含义       |
|----------+------------|
| Title    | 标题       |
| Author   | 作者       |
| Year     | 年份       |
| Conf     | 会议或期刊 |
| Group    | 研究小组   |
| Keywords | 关键字     |
| Link     | 文件链接   |

显示的时候, 针对这一类型的内容创建了根据小组显示的视图(Views), 在现有的三个小组的Book下添加相应Page即可. 如 "~/publications/group/ssl". 视图的显示还没有进行美 化,所以现在还没有加入到Book中.

* 文献管理
** 目的
   提供一个实验室内部共享的文献管理系统,实现论文上传,分类检索的功能.
** 思路A
   利用Drupal本身进行开发. 目前安装了"Biblo"模块,可在登陆后选择"[[http://kyhcs.ustcsz.edu.cn/biblio][Biblo]]"进入. 对现有的Publication进行了导入, 可以按照年份,作者,类型,标题,关键字进行排序,筛选和检索, 支持Bibtex文件导入. 从功能上看,
能够基本满足我们的需要. 如果采用的话, 需要简化内容添加的界面, 其自带的字段相对来说过于详细了.添加的内容比较局限,如果涉及图片视频等资料只能通过上传附件形式,没有显式的支持.搜索功能不够强.
** 思路B
   使用DSpace.效果可以见[[http://embedded.ustcsz.edu.cn:8080/dspace/][嵌入式系统实验室]](http://embedded.ustcsz.edu.cn:8080/dspace/)的页面. 和Drupal相比,DSpace更倾向于内容的分类管理,用户存在感不强,但是对不同类型的文档,如图片,视频的支持更好.
** 思路C
   自行开发系统.需要涉及的功能包括:
   1. 可配置的元数据创建, 即提供不同类型内容的创建以及新增类型的功能
   2. 搜索功能.除了根据年份,作者等信息外,还要能根据用户添加的Tag进行搜索
   3. 对不同类型文档的处理,如图片,PDF文件,包含多个文件的如HTML,图文混排的文本
   4. 导入/导出以及附件的处理
** 比较
   B和C都涉及和现有网站用户资料的整合, 这方面找到一些导出Drupal用户数据到Discuz!的介绍, 应该是可以实现的, 即可以用现有的账号登陆. A是现在看来最简捷的实现, 欠缺的地方在于搜索功能, 准备调研下Drupal搜索功能的开发再具体说明一下.

